routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::group(['prefix' => ''], function() {

    Route::group(['middleware' => 'auth'], function() {
        Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

        Route::resource('company', App\Http\Controllers\CompanyController::class);
        Route::resource('employee', App\Http\Controllers\EmployeeController::class);
    });
});

app/Models/Employee.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Employee extends Model
{
    use HasFactory;
    
    public $timestamps = true;
    protected $fillable = [
        "user_id",
        "company_id",
        "first_name", 
        "last_name",
        "phone",
        "created_by",
        "updated_by"
    ];
}

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Employee;
use App\Models\User;
use App\Models\Role;

use Auth;


class EmployeeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $employee = Employee::select([
            'employees.*',
            'users.email',
            'companies.name as company_name'
        ])->join('users','users.id','employees.user_id')
        ->join('companies','companies.id','employees.company_id')
        ->whereNull('users.deleted_at')
        ->latest()->paginate(10);
    
        return view('employee.index',compact('employee'))
            ->with('i', (request()->input('page', 1) - 1) * 10);
    }
     
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('employee.create');
    }
    
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'first_name'    => 'required|string',
            'last_name'     => 'required|string',
            'email'         => 'sometimes|email|unique:users,email,NULL,id,deleted_at,NULL',
            'company_id'    => 'required|exists:companies,id',
            'phone'         => 'sometimes',
        ]);

        $user               = new User();
        $user->email        = $request->input('email');
        $user->password     = bcrypt('password');
        $user->role_id      = Role::where('role_name', 'employee')->first()->id ?? 1;
        $user->created_by   = Auth::user()->id;
        if($user->save()) {
            $request['user_id']     = $user->id;
            $request['created_by']  = Auth::user()->id;
            Employee::create($request->all());
        }
     
        return redirect()->route('employee.index')
                        ->with('success','Employee created successfully.');
    }
     
    /**
     * Display the specified resource.
     *
     * @param  \App\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function show(Employee $employee)
    {
        $employee = $employee->select([
            'employees.*',
            'users.email',
            'companies.name as company_name'
        ])
        ->join('users','users.id','employees.user_id')
        ->join('companies','companies.id','employees.company_id')
        ->first();

        return view('employee.show',compact('employee'));
    } 
     
    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function edit(Employee $employee)
    {
        $employee = $employee->select([
            'employees.*',
            'users.email',
            'companies.name as company_name'
        ])
        ->join('users','users.id','employees.user_id')
        ->join('companies','companies.id','employees.company_id')
        ->first();
        return view('employee.edit',compact('employee'));
    }
    
    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Employee $employee)
    {
        $user               = User::where('id',$employee->user_id)->first();
        $request->validate([
            'first_name'    => 'required|string',
            'last_name'     => 'required|string',
            'email'         => "sometimes|email|unique:users,email,$user->id,id,deleted_at,NULL",
            'company_id'    => 'required|exists:companies,id',
            'phone'         => 'sometimes',
        ]);

        $user->email        = $request->input('email');
        $user->updated_by   = Auth::user()->id;
        if($user->save()) {
            $request['user_id']     = $user['id'];
            $request['created_by']  = Auth::user()->id;
            $request['updated_by']  = Auth::user()->id;
            $employee->update($request->all());
        }
    
        return redirect()->route('employee.index')
                        ->with('success','Employee updated successfully');
    }
    
    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function destroy(Employee $employee)
    {
        $user = User::where('id', $employee->user_id);
        $user->delete();
    
        return redirect()->route('employee.index')
                        ->with('success','Employee deleted successfully');
    }

}

resources/views/employee/create.blade.php
@extends('layouts.admin')
@section('title', 'Add Employee')
@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('employee.index') }}"> Back</a>
        </div>
    </div>
</div>
   
@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Warning!</strong> There were some problems with your input.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

<form action="{{ route('employee.store') }}" method="POST" enctype="multipart/form-data">
    @csrf
  
     <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-8">
            <div class="form-group">
                <strong>Email:</strong>
                <input type="email" name="email" class="form-control" value="{{ old('email') }}" placeholder="Email">
            </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-8">
            <div class="form-group">
                <strong>First Name:</strong>
                <input type="text" name="first_name" class="form-control" value="{{ old('first_name') }}" placeholder="First Name">
            </div>
        </div>
        
        <div class="col-xs-12 col-sm-12 col-md-8">
            <div class="form-group">
                <strong>Last Name:</strong>
                <input type="text" name="last_name" class="form-control" value="{{ old('last_name') }}" placeholder="Last Name">
            </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-8">
            <div class="form-group">
                <strong>Phone:</strong>
                <input type="text" name="phone" class="form-control" value="{{ old('phone') }}" placeholder="Phone">
            </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-8">
            <div class="form-group">
                <strong>Company:</strong>
                <select name="company_id" id="company_id" class="form-control" required>
                    <option value="" hidden>Choose Company </option>
                    @foreach(App\Models\Company::pluck('name','id') as $id => $label)
                        <option value="{{ $id }}" >{{ $label }}</option>
                    @endforeach
                </select>
            </div>
        </div>
       
        <div class="col-xs-12 col-sm-12 col-md-8 text-left">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>
   
</form>
      
@endsection

resources/views/employee/edit.blade.php
@extends('layouts.admin')
@section('title', 'Edit')
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('employee.index') }}"> Back</a>
            </div>
        </div>
    </div>
   
    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Warning!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
  
    <form action="{{ route('employee.update',$employee->id) }}" method="POST" enctype="multipart/form-data">
        @csrf
        @method('PUT')
   
         <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Email:</strong>
                    <input type="text" name="email" value="{{ $employee->email }}" class="form-control" placeholder="Email">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>First Name:</strong>
                    <input type="text" name="first_name" value="{{ $employee->first_name }}" class="form-control" placeholder="First Name">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Last Name:</strong>
                    <input type="text" name="last_name" value="{{ $employee->last_name }}" class="form-control" placeholder="Last Name">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Phone:</strong>
                    <input type="text" name="phone" value="{{ $employee->phone }}" class="form-control" placeholder="Last Name">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Company Name:</strong>
                    <select name="company_id" id="company_id" class="form-control" required>
                        <option value="" hidden>Choose Company </option>
                        @foreach(App\Models\Company::pluck('name','id') as $id => $label)
                            <option value="{{ $id }}" <?= $employee->company_id === $id ? 'selected' : '' ?> >{{ $label }}</option>
                        @endforeach
                    </select>
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 text-left">
              <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>
   
    </form>
@endsection

resources/views/employee/index.blade.php
@extends('layouts.admin')
@section('title', 'Employee')
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-right">
                <a class="btn btn-success" href="{{ route('employee.create') }}"> Create New Employee</a>
            </div>
        </div>
    </div>
   
    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif
   
    <table class="table table-bordered">
        <tr>
            <th>No</th>
            <th>Company Name</th>
            <th>Fullname</th>
            <th>Email</th>
            <th>Phone</th>
            <th>Created At</th>
            <th width="280px">Action</th>
        </tr>
        @foreach ($employee as $key => $value)
        <tr>
            <td>{{ ++$i }}</td>
            <td>{{ $value->company_name }}</td>
            <td>{{ $value->first_name }} {{ $value->last_name }}</td>
            <td>{{ $value->email }}</td>
            <td>{{ $value->phone }}</td>
            <td>{{ $value->created_at }}</td>
            <td>
                <form action="{{ route('employee.destroy',$value->id) }}" method="POST">
   
                    <a class="btn btn-info" href="{{ route('employee.show',$value->id) }}">Show</a>
    
                    <a class="btn btn-primary" href="{{ route('employee.edit',$value->id) }}">Edit</a>
   
                    @csrf
                    @method('DELETE')
      
                    <button type="submit" class="btn btn-danger">Delete</button>
                </form>
            </td>
        </tr>
        @endforeach
    </table>
  
    {!! $employee->links() !!}
      
@endsection

resources/views/employee/show.blade.php
@extends('layouts.admin')
@section('title', 'Show')
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('employee.index') }}"> Back</a>
            </div>
        </div>
    </div>
   
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Company Name:</strong>
                {{ $employee->company_name }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>First Name:</strong>
                {{ $employee->first_name }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Last Name:</strong>
                {{ $employee->last_name }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Email:</strong>
                {{ $employee->email }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Phone:</strong>
                {{ $employee->phone }}
            </div>
        </div>
    </div>
@endsection