routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::group(['prefix' => ''], function() {

    Route::group(['middleware' => 'auth'], function() {
        Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

        Route::resource('company', App\Http\Controllers\CompanyController::class);
        Route::resource('employee', App\Http\Controllers\EmployeeController::class);
    });
});

app/Models/Company.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Company extends Model
{
    use HasFactory, SoftDeletes;
    
    public $timestamps = true;
    protected $fillable = [
        "name",
        "email", 
        "logo",
        "website", 
        "created_by",
        "updated_by"
    ];

    public function employee(){ 
        return $this->hasMany('App\Models\Employee','company_id')
        ->join('users', 'users.id', 'employees.user_id')
        ->whereNull('deleted_at');
    }
}

app/Http/Controllers/CompanyController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;
use App\Models\Company;
use Auth;

class CompanyController extends Controller
{
     /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $company = Company::latest()->paginate(10);
    
        return view('company.index',compact('company'))
            ->with('i', (request()->input('page', 1) - 1) * 10);
    }
     
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('company.create');
    }
    
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name'      => "required|string",
            'email'     => 'sometimes|email|unique:companies,email,NULL,id,deleted_at,NULL',
            'logos'     => "nullable|mimes:jpeg,png,jpg,gif,svg|dimensions:min_width=150,min_height=150",
            'website'   => "sometimes|url",
        ]);

        $dir_upload = '/uploads/company/';
        $dir        = base_path().'/public'.$dir_upload;
        if (! File::exists($dir)) {
            File::makeDirectory($dir,0777,true);
        }

        if($request->hasFile('logos')){
            $file = $request->file('logos');
            $filename = $dir_upload.$request['name'].'.'.$file->getClientOriginalExtension();
            $file->move($dir, $filename);
            $request['logo'] = $filename;
        }
        $request['created_by'] = Auth::user()->id;

        Company::create($request->all());
     
        return redirect()->route('company.index')
                        ->with('success','Company created successfully.');
    }
     
    /**
     * Display the specified resource.
     *
     * @param  \App\Company  $company
     * @return \Illuminate\Http\Response
     */
    public function show(Company $company)
    {
        $company = Company::with(['employee'])->where('id', $company->id)->first();
        return view('company.show',compact('company'));
    } 
     
    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Company  $company
     * @return \Illuminate\Http\Response
     */
    public function edit(Company $company)
    {
        return view('company.edit',compact('company'));
    }
    
    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Company  $company
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Company $company)
    {
        $request->validate([
            'name'      => "required|string",
            'email'     => "sometimes|email|unique:companies,email,$company->id,id,deleted_at,NULL",
            'logos'     => "nullable|image|mimes:jpeg,png,jpg,gif,svg|dimensions:min_width=150,min_height=150",
            'website'   => "sometimes|url",
        ]);

        $dir_upload = '/uploads/company/';
        $dir        = base_path().'/public'.$dir_upload;
        if (! File::exists($dir)) {
            File::makeDirectory($dir,0777,true);
        }
        
        if($request->hasFile('logos')){
            $file = $request->file('logos');
            $filename = $dir_upload.$request['name'].'.'.$file->getClientOriginalExtension();
            $file->move($dir, $filename);
            $request['logo'] = $filename;
        }
        $request['updated_by'] = Auth::user()->id;
       
        $company->update($request->all());
    
        return redirect()->route('company.index')
                        ->with('success','Company updated successfully');
    }
    
    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Company  $employee
     * @return \Illuminate\Http\Response
     */
    public function destroy(Company $company)
    {
        $company->delete();
    
        return redirect()->route('company.index')
                        ->with('success','Company deleted successfully');
    }
}

resources/views/company/create.blade.php
@extends('layouts.admin')
@section('title', 'Add Company')
@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('company.index') }}"> Back</a>
        </div>
    </div>
</div>
   
@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Warning!</strong> There were some problems with your input.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

<form action="{{ route('company.store') }}" method="POST" enctype="multipart/form-data">
    @csrf
  
     <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-8">
            <div class="form-group">
                <strong>Name:</strong>
                <input type="text" name="name" class="form-control" value="{{ old('name') }}" placeholder="Name">
            </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-8">
            <div class="form-group">
                <strong>Email:</strong>
                <input type="email" name="email" class="form-control" value="{{ old('email') }}" placeholder="Email">
            </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-8">
            <div class="form-group">
                <strong>Logo:</strong>
                <input type="file" name="logos" class="form-control" accept="image/*">
            </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-8">
            <div class="form-group">
                <strong>Website:</strong>
                <input type="text" name="website" class="form-control" value="{{ old('website') }}" placeholder="Website">
            </div>
        </div>
       
        <div class="col-xs-12 col-sm-12 col-md-8 text-left">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>
   
</form>
      
@endsection

resources/views/company/edit.blade.php
@extends('layouts.admin')
@section('title', 'Edit')
@section('contentJs')
<script>
    $(document).ready(function(){
        $('#modal_contact').on('click', function() {
            var $el = $(this);
            var $link = $el.data('username');
            $(".modal-title").html($link);
            $(".show-image").attr("src",$link);
        });
    });
</script>
@endsection
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('company.index') }}"> Back</a>
            </div>
        </div>
    </div>
   
    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Warning!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
  
    <form action="{{ route('company.update',$company->id) }}" method="POST" enctype="multipart/form-data">
        @csrf
        @method('PUT')
   
         <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Name:</strong>
                    <input type="text" name="name" value="{{ $company->name }}" class="form-control" placeholder="Name">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Email:</strong>
                    <input type="text" name="email" value="{{ $company->email }}" class="form-control" placeholder="Email">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Logo:</strong>
                    <input type="file" name="logos" class="form-control" accept="image/*">
                    <a id="modal_contact" data-userName="{{ $company->logo }}" data-toggle="modal" href="#option_contact">
                        <i class="fa fa-check-square-o"></i> Show Image
                    </a>
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Website:</strong>
                    <input type="text" name="website" value="{{ $company->website }}" class="form-control" placeholder="Email">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 text-left">
              <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>
    </form>

    <div class="modal fade" id="option_contact" tabindex="-1">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button aria-hidden="true" class="close" data-dismiss="modal"
                    type="button"></button>
                    <h4 class="modal-title"></h4>
                </div>
                <div class="modal-body text-center">
                    <img src='' width="300px" height="300px" class="img-fluid cursor-pointer show-image">
                </div>
                <div class="modal-footer">
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/company/index.blade.php
@extends('layouts.admin')
@section('title', 'Company')
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-right">
                <a class="btn btn-success" href="{{ route('company.create') }}"> Create New Company</a>
            </div>
        </div>
    </div>
   
    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif
   
    <table class="table table-bordered">
        <tr>
            <th>No</th>
            <th>Name</th>
            <th>Email</th>
            <th>Website</th>
            <th width="280px">Action</th>
        </tr>
        @foreach ($company as $key => $value)
        <tr>
            <td>{{ ++$i }}</td>
            <td>{{ $value->name }}</td>
            <td>{{ $value->email }}</td>
            <td>{{ $value->website }}</td>
            <td>
                <form action="{{ route('company.destroy',$value->id) }}" method="POST">
   
                    <a class="btn btn-info" href="{{ route('company.show',$value->id) }}">Show</a>
    
                    <a class="btn btn-primary" href="{{ route('company.edit',$value->id) }}">Edit</a>
   
                    @csrf
                    @method('DELETE')
      
                    <button type="submit" class="btn btn-danger">Delete</button>
                </form>
            </td>
        </tr>
        @endforeach
    </table>
  
    {!! $company->links() !!}
      
@endsection

resources/views/company/show.blade.php
@extends('layouts.admin')
@section('title', 'Show')
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('company.index') }}"> Back</a>
            </div>
        </div>
    </div>
   
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Name:</strong>
                {{ $company->name }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Email:</strong>
                {{ $company->email }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Logo:</strong>
                <img src='{{ asset("$company->logo") }}' width="150px" height="150px" class="img-fluid cursor-pointer">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Website:</strong>
                {{ $company->email }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Employee:</strong>
                <ul>
                @foreach($company->employee as $index => $value)
                    <li> {{ $value->first_name }} {{ $value->last_name }}</li>    
                @endforeach
                </ul>
            </div>
        </div>
    </div>
@endsection