routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::group(['prefix' => ''], function() {

    Route::group(['middleware' => 'auth'], function() {
        Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

        Route::resource('company', App\Http\Controllers\CompanyController::class);
        Route::resource('employee', App\Http\Controllers\EmployeeController::class);
    });
});

resources/views/layouts/admin.blade.php
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="csrf-token" content="{{ csrf_token() }}">
		<title>{{ env("APP_NAME") }} - @yield('title')</title>
		<meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
		<link rel="stylesheet" href="{{ asset('plugins/bootstrap/css/bootstrap.min.css', ENV('SSL_FLAG')) }}">
		<link rel="stylesheet" href="{{ asset('plugins/font-awesome/css/font-awesome.min.css', ENV('SSL_FLAG')) }}">
		<link rel="stylesheet" href="{{ asset('plugins/Ionicons/css/ionicons.min.css', ENV('SSL_FLAG')) }}">
		<link rel="stylesheet" href="{{ asset('plugins/iCheck/all.css', ENV('SSL_FLAG')) }}">
		<link rel="stylesheet" href="{{ asset('plugins/select2/css/select2.min.css', ENV('SSL_FLAG')) }}">
		<link rel="stylesheet" href="{{ asset('plugins/select2/css/select2-bootstrap.min.css', ENV('SSL_FLAG')) }}">
		<link rel="stylesheet" href="{{ asset('plugins/datepicker/css/bootstrap-datepicker3.min.css', ENV('SSL_FLAG')) }}">
		<link rel="stylesheet" href="{{ asset('plugins/datatables/datatables.net-bs/css/dataTables.bootstrap.min.css', ENV('SSL_FLAG')) }}">
		<link rel="stylesheet" href="{{ asset('plugins/admin-lte/css/AdminLTE.min.css', ENV('SSL_FLAG')) }}">
		<link rel="stylesheet" href="{{ asset('plugins/admin-lte/css/skins/_all-skins.min.css', ENV('SSL_FLAG')) }}">
		<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
		<link rel="stylesheet" href="https://cdn.jsdelivr.net/bootstrap.tagsinput/0.4.2/bootstrap-tagsinput.css" />
		<link rel='stylesheet' href='https://cdn.jsdelivr.net/npm/sweetalert2@10.10.1/dist/sweetalert2.min.css'>

		<link rel="stylesheet" href="{{ asset('css/app.css', ENV('SSL_FLAG')) }}">

		<style type="text/css">
			.loader {
			  border: 16px solid #f3f3f3;
			  border-radius: 50%;
			  border-top: 16px solid blue;
			  border-bottom: 16px solid blue;
			  width: 60px;
			  height: 60px;
			  -webkit-animation: spin 2s linear infinite;
			  animation: spin 2s linear infinite;
			}

			@-webkit-keyframes spin {
			  0% { -webkit-transform: rotate(0deg); }
			  100% { -webkit-transform: rotate(360deg); }
			}

			@keyframes spin {
			  0% { transform: rotate(0deg); }
			  100% { transform: rotate(360deg); }
			}
		</style>
		@yield('contentCss')
	</head>
	<body class="hold-transition skin-blue sidebar-mini">
		<div class="wrapper">
			<header class="main-header">
				<a href="{{ url('/') }}" class="logo" target="_blank">
					<span class="logo-mini"><b>X</b></span>
					<span class="logo-lg">
						<b>{{ env("APP_NAME") }}</b>
					</span>
				</a>
				<nav class="navbar navbar-static-top">
					<a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
					</a>
					<div class="navbar-custom-menu">
						<ul class="nav navbar-nav">
							<li class="dropdown user user-menu">
								<a href="#" class="dropdown-toggle" data-toggle="dropdown">
								<span class="hidden-xs">{{ Auth::User()->email }}</span>
								</a>
								<ul class="dropdown-menu">
									<li class="user-header">
										<p>
											{{ Auth::User()->email }}
										</p>
									</li>
									<li class="user-footer">
										<div class="row">
											<div class="col-md-7">
												<a href="{{ url('change-password') }}" class="btn btn-block btn-default">Ubah Password</a>
											</div>
											<div class="col-md-5">
                                            <a class="dropdown-item btn btn-block btn-default" href="{{ route('logout') }}"
                                                onclick="event.preventDefault();
                                                                document.getElementById('logout-form').submit();">
                                                    {{ __('Logout') }}
                                                </a>

                                                <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                                    @csrf
                                                </form>
											</div>
										</div>
									</li>
								</ul>
							</li>
						</ul>
					</div>
				</nav>
			</header>
			<aside class="main-sidebar">
				@include('layouts.sidebar')
			</aside>
			<div class="content-wrapper">
				<section class="content main-content">
					<div class="box box-solid">
						<div class="box-header with-border">
							<h3 class="box-title">@yield('title')</h3>
						</div>
						<div class="box-body" style="min-height: 550px;">
							<div id="mainAlert"></div>
							@yield('content')
						</div>
					</div>
				</section>
			</div>
			<footer class="main-footer">
				<div class="pull-right hidden-xs">
					<b>Version</b> {{ env("VERSIONS") }}
				</div>
				{{ date('Y') }} &copy; Created by <strong><span><a href="/">{{ env("APP_COPY_RIGHT") }}</a></span></strong>.
			</footer>
		</div>
		<script src="{{ asset('plugins/jquery/jquery.min.js', ENV('SSL_FLAG')) }}"></script>
		<script src="{{ asset('plugins/bootstrap/js/bootstrap.min.js', ENV('SSL_FLAG')) }}"></script>
		<script src="{{ asset('plugins/jquery-slimscroll/jquery.slimscroll.min.js', ENV('SSL_FLAG')) }}"></script>
		<script src="{{ asset('plugins/fastclick.js', ENV('SSL_FLAG')) }}"></script>
		<script src="{{ asset('plugins/admin-lte/js/adminlte.min.js', ENV('SSL_FLAG')) }}"></script>

		<script src="{{ asset('plugins/moment.js', ENV('SSL_FLAG')) }}"></script>
		<script src="{{ asset('plugins/iCheck/icheck.min.js', ENV('SSL_FLAG')) }}"></script>
		<script src="{{ asset('plugins/select2/js/select2.min.js', ENV('SSL_FLAG')) }}"></script>
		<script src="{{ asset('plugins/datepicker/js/bootstrap-datepicker.min.js', ENV('SSL_FLAG')) }}"></script>
		<script src="{{ asset('plugins/datatables/datatables.net/js/jquery.dataTables.min.js', ENV('SSL_FLAG')) }}"></script>
		<script src="{{ asset('plugins/datatables/datatables.net-bs/js/dataTables.bootstrap.min.js', ENV('SSL_FLAG')) }}"></script>
		<script src="{{ asset('plugins/jquery.blockUI.js', ENV('SSL_FLAG')) }}"></script>
		<script src="{{ asset('js/app.js', ENV('SSL_FLAG')) }}"></script>
		<script src="https://cdn.datatables.net/buttons/1.6.1/js/dataTables.buttons.min.js"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
		<script src="https://cdn.datatables.net/buttons/1.6.1/js/buttons.html5.min.js"></script>
		<script src="https://cdn.jsdelivr.net/bootstrap.tagsinput/0.4.2/bootstrap-tagsinput.min.js"></script>
		<script src="https://cdn.jsdelivr.net/npm/sweetalert2@10.10.1/dist/sweetalert2.all.min.js"></script>
		<script>
			$('.datepicker-custome').datepicker({
				format: 'yyyy-mm-dd',
				autoclose: true,
				clearBtn: true,
				todayHighlight: true,
			});
		</script>
		@yield('contentJs')
	</body>
</html>

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

      <!-- Scripts -->
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <style type="text/css">
			.loader {
			  border: 16px solid #f3f3f3;
			  border-radius: 50%;
			  border-top: 16px solid blue;
			  border-bottom: 16px solid blue;
			  width: 60px;
			  height: 60px;
			  -webkit-animation: spin 2s linear infinite;
			  animation: spin 2s linear infinite;
			}

			@-webkit-keyframes spin {
			  0% { -webkit-transform: rotate(0deg); }
			  100% { -webkit-transform: rotate(360deg); }
			}

			@keyframes spin {
			  0% { transform: rotate(0deg); }
			  100% { transform: rotate(360deg); }
			}
		</style>
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav me-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ms-auto">
                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/sidebar.blade.php
<?php
	$currentAction = Route::currentRouteAction();
	list($controller, $method) = explode('@', $currentAction);
	$controller = str_replace("App\\Http\\Controllers\\", "", $controller);
?>
<section class="sidebar">
	<ul class="sidebar-menu" data-widget="tree">
		<li class="header">MAIN NAVIGATION</li>
		<li class="{{ ($controller=='HomeController'?'active':'') }}">
			<a href="{{ url('home') }}">
			<i class="fa fa-dashboard"></i> <span>Dashboard</span>
			</a>
		</li>

		<hr>

		@if(in_array(Auth::User()->role_id, [1]))
            <li class="{{ ($controller=='CompanyController'?'active':'') }}">
                <a href="{{ route('company.index') }}">
                <i class="fa fa-building-o"></i> <span>Company</span>
                </a>
            </li>
            <li class="{{ ($controller=='EmployeeController'?'active':'') }}">
                <a href="{{ url('employee') }}">
                <i class="fa fa-user"></i> <span>Employee</span>
                </a>
            </li>
		@endif
		
	</ul>
</section>